/**
 * Stray files.
 *
 * A range that adds a scratch script, a debug log, an editor backup, a
 * coverage directory, a build artefact or a copied-aside file added it because
 * an agent was working, not because anyone decided to keep it. This check reads
 * the paths `base..candidate` ADDS and reports two separate things:
 *
 * - a path whose name matches a shape in `STRAY_SHAPES` - the fix is to delete
 *   the file;
 * - a path the repository's own ignore rules would exclude, though it is
 *   tracked - the fix is either to delete the file or to correct the rules,
 *   because the tree and the rules disagree.
 *
 * Only ADDED paths count. A modification, or a rename of a file, is not an
 * addition, so an ordinary rename of a legitimately-named file is never a
 * finding. The paths come from git's diff of the two commits, never from the
 * working tree, so a file a developer has locally is not a finding against a
 * candidate that does not contain it.
 */

import { execFile } from "node:child_process";

import type { CheckRecord } from "./index.js";

const NAME = "RT-05";

/** Where to look, and which two revisions bound the range. */
export interface StrayFilesOptions {
  /** The git repository to run in. */
  readonly cwd: string;
  /** The revision the range starts after. */
  readonly base: string;
  /** The revision the range ends at. */
  readonly candidate: string;
}

/** One stated stray shape. */
export interface StrayShape {
  /** Short stable name; it is what a finding prints. */
  readonly name: string;
  /** Why a path of this shape is probably not meant to be kept. */
  readonly description: string;
  /** Tested against the added path, relative to the repository root, with `/` separators. */
  readonly pattern: RegExp;
}

/**
 * The stray shapes. The list is read each time the check runs, so a consumer
 * with its own conventions appends an entry (`STRAY_SHAPES.push({...})`)
 * instead of forking the matcher. Order is only the order findings print in.
 */
export const STRAY_SHAPES: StrayShape[] = [
  {
    name: "log-file",
    description: "a .log file is output of a run, not source",
    pattern: /\.log$/i,
  },
  {
    name: "editor-backup",
    description: "an editor or tool backup (.bak, .orig, .swp, .swo, trailing ~)",
    pattern: /(?:\.(?:bak|orig|swp|swo)|~)$/i,
  },
  {
    name: "set-aside-copy",
    description: "a copy set aside beside the original, such as 'index 2.ts' or 'index copy.ts'",
    pattern: /(?:^|\/)[^/]*[^/ ] (?:\d+|copy(?: \d+)?|\(\d+\))(?:\.[^/ ]*)?$/i,
  },
  {
    name: "scratch-script",
    description: "a scratch or temporary script (scratch.*, tmp.*, debug.*)",
    pattern: /(?:^|\/)(?:scratch|tmp|temp|debug)(?:[-_.][^/]*)?\.(?:[cm]?[jt]sx?|py|sh|rb)$/i,
  },
  {
    name: "coverage-output",
    description: "anything under coverage/ is generated by a test run",
    pattern: /(?:^|\/)coverage\//,
  },
  {
    name: "build-output",
    description: "anything under dist/ or build/ is a build artefact",
    pattern: /(?:^|\/)(?:dist|build)\//,
  },
  {
    name: "os-metadata",
    description: "operating-system folder metadata (.DS_Store, Thumbs.db)",
    pattern: /(?:^|\/)(?:\.DS_Store|Thumbs\.db)$/,
  },
];

function runGit(
  cwd: string,
  args: readonly string[],
  input?: string,
  okCodes: readonly number[] = [0],
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const child = execFile(
      "git",
      args as string[],
      { cwd, maxBuffer: 1024 * 1024 * 1024, encoding: "buffer" },
      (error, stdout, stderr) => {
        if (error) {
          const code = (error as { code?: unknown }).code;
          if (typeof code === "number" && okCodes.includes(code)) {
            resolve(stdout);
            return;
          }
          const detail = stderr.toString("utf8").trim();
          reject(new Error(detail.length > 0 ? detail : error.message));
          return;
        }
        resolve(stdout);
      },
    );
    if (input !== undefined) {
      child.stdin?.on("error", () => undefined);
      child.stdin?.end(input);
    }
  });
}

/** Escape everything outside printable ASCII so a name cannot replay a control sequence. */
function escapeText(text: string): string {
  let escaped = "";
  for (const char of text) {
    const codePoint = char.codePointAt(0) ?? 0;
    if (codePoint >= 0x20 && codePoint <= 0x7e) {
      escaped += char;
    } else {
      escaped += `\\u{${codePoint.toString(16).padStart(4, "0")}}`;
    }
  }
  return escaped;
}

function quote(text: string): string {
  return `"${escapeText(text)}"`;
}

function decodePath(bytes: Buffer): string {
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    return bytes.toString("latin1");
  }
}

function splitNul(out: Buffer): string[] {
  const paths: string[] = [];
  let start = 0;
  for (let i = 0; i < out.length; i += 1) {
    if (out[i] === 0) {
      if (i > start) {
        paths.push(decodePath(out.subarray(start, i)));
      }
      start = i + 1;
    }
  }
  return paths;
}

async function resolveCommit(cwd: string, revision: string): Promise<string> {
  if (revision.length === 0 || revision.startsWith("-")) {
    throw new Error(`revision ${quote(revision)} names no commit`);
  }
  try {
    const out = await runGit(cwd, ["rev-parse", "--verify", "--quiet", `${revision}^{commit}`]);
    const hash = out.toString("utf8").trim();
    if (hash.length === 0) {
      throw new Error("empty answer");
    }
    return hash;
  } catch (error) {
    throw new Error(`revision ${quote(revision)} names no commit: ${(error as Error).message}`);
  }
}

/** The paths the range adds: status A only, with renames detected so a rename is not one. */
async function addedPaths(root: string, base: string, candidate: string): Promise<string[]> {
  const label = `${base.slice(0, 12)} and ${candidate.slice(0, 12)}`;
  let ancestor: string;
  try {
    ancestor = (await runGit(root, ["merge-base", base, candidate])).toString("utf8").trim();
  } catch (error) {
    throw new Error(`no merge base of ${label}: ${(error as Error).message}`);
  }
  if (ancestor.length === 0) {
    throw new Error(`no merge base of ${label}`);
  }
  try {
    const out = await runGit(root, [
      "-c",
      "core.quotePath=false",
      "diff",
      "--no-ext-diff",
      "--no-textconv",
      "--no-color",
      "-M",
      "-l0",
      "--diff-filter=A",
      "--name-only",
      "-z",
      ancestor,
      candidate,
      "--",
    ]);
    return splitNul(out);
  } catch (error) {
    throw new Error(`could not read the paths added by the range: ${(error as Error).message}`);
  }
}

/** Which of the paths the repository's ignore rules would exclude, tracked or not. */
async function ignoredPaths(root: string, paths: readonly string[]): Promise<Set<string>> {
  if (paths.length === 0) {
    return new Set();
  }
  try {
    const out = await runGit(
      root,
      ["check-ignore", "--no-index", "-z", "--stdin"],
      paths.map((path) => `${path}\0`).join(""),
      [0, 1],
    );
    return new Set(splitNul(out));
  } catch (error) {
    throw new Error(`could not read the ignore rules: ${(error as Error).message}`);
  }
}

/**
 * Check the paths `base..candidate` adds for stray shapes and for paths the
 * ignore rules would exclude. Fails closed: a revision that names no commit,
 * or any git invocation that fails, is a `fail` record naming the cause -
 * never a `pass`, and never a thrown error.
 */
export async function checkStrayFiles(options: StrayFilesOptions): Promise<CheckRecord> {
  try {
    const { cwd, base, candidate } = options;
    const baseCommit = await resolveCommit(cwd, base);
    const candidateCommit = await resolveCommit(cwd, candidate);
    const root = (await runGit(cwd, ["rev-parse", "--show-toplevel"])).toString("utf8").replace(/\r?\n$/, "");

    const added = (await addedPaths(root, baseCommit, candidateCommit)).sort();
    const shapes = [...STRAY_SHAPES];
    const evidence: string[] = [];

    for (const path of added) {
      for (const shape of shapes) {
        shape.pattern.lastIndex = 0;
        if (shape.pattern.test(path)) {
          evidence.push(`${quote(path)} matches stray shape ${quote(shape.name)}: ${shape.description}`);
        }
      }
    }

    const ignored = await ignoredPaths(root, added);
    for (const path of added) {
      if (ignored.has(path)) {
        evidence.push(
          `${quote(path)} is added but the ignore rules exclude it: delete the file or correct the ignore rules`,
        );
      }
    }

    if (evidence.length > 0) {
      return { name: NAME, status: "fail", evidence };
    }
    return {
      name: NAME,
      status: "pass",
      evidence: [
        `${added.length} path(s) added in ${quote(base)}..${quote(candidate)} match no stray shape and no ignore rule`,
      ],
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { name: NAME, status: "fail", evidence: [escapeText(message)] };
  }
}
